CREATE DATABASE AccountDB;
USE AccountDB;
CREATE TABLE AccountsInfo(
	UserID int AUTO_INCREMENT NOT NULL,
	GameID int NOT NULL,
	ProtectID int NOT NULL,
	Accounts VARCHAR(31) NOT NULL,
	RegAccounts VARCHAR(31) NOT NULL,
	UnderWrite VARCHAR(63) NOT NULL,
	LogonPass CHAR(32) NOT NULL,
	InsurePass CHAR(32) NOT NULL,
	SpreaderID VARCHAR(31) NOT NULL,
	FaceID smallint NOT NULL,
	Experience int NOT NULL,
	UserRight int NOT NULL,
	MasterRight int NOT NULL,
	ServiceRight int NOT NULL,
	MasterOrder tinyint NOT NULL,
	MemberOrder tinyint NOT NULL,
	MemberOverDate datetime NOT NULL,
	Loveliness int NOT NULL,
	Gender tinyint NOT NULL,
	Nullity bit NOT NULL,
	StunDown bit NOT NULL,
	MoorMachine tinyint NOT NULL,
	MachineSerial CHAR(32) NOT NULL,
	WebLogonTimes int NOT NULL,
	GameLogonTimes int NOT NULL,
	RegisterIP VARCHAR(15) NOT NULL,
	LastLogonIP VARCHAR(15) NOT NULL,
	RegisterDate DATETIME NOT NULL,
	LastLogonDate DATETIME NOT NULL,
	CustomFaceVer tinyint NULL,
	c_email VARCHAR(50) NULL,
	PRIMARY KEY (UserID)
);
