DROP DATABASE IF EXISTS `AccountsFace`;
CREATE DATABASE AccountDB;
USE AccountDB;
CREATE TABLE AccountsFace (
	ID INT NOT NULL AUTO_INCREMENT,
	USERID INT NOT NULL COMMENT '用户标识',
	CustomFace NVARCHAR(100) NOT NULL,
	InsertTime DATETIME NOT NULL DEFAULT NOW(),
	InsertAddr NVARCHAR(15) NOT NULL COMMENT '登录地址',
	InserMachine NVARCHAR(12) NOT NULL,	
	PRIMARY KEY (ID)	
);



CREATE TABLE AccountsInfo(
	UserID INT NOT NULL AUTO_INCREMENT COMMENT '用户标识',
	Accounts NVARCHAR(16) NOT NULL COMMENT '用户账号(手机号码)',
	NickName NVARCHAR(31) NOT NULL COMMENT '用户昵称',
	SpreaderID NVARCHAR(16) NOT NULL DEFAULT "0" COMMENT '推广员标识',
	UnderWrite NVARCHAR(63) NOT NULL DEFAULT ""  COMMENT '个性签名',
	Compellation NVARCHAR(16) NOT NULL DEFAULT "N''"  COMMENT '真实姓名',
	LoginPass NCHAR(32) NOT NULL COMMENT '登录密码',
	FaceID SMALLINT NOT NULL DEFAULT "0"  COMMENT '头像标识',
	CustomID INT NOT NULL DEFAULT "0"  COMMENT '自定标识',
	IsOnline BIT NOT NULL DEFAULT "0"  COMMENT '在线标识',
	CustomFaceVer TINYINT NOT NULL DEFAULT "0"  COMMENT '头像版本',
	Gender TINYINT NOT NULL DEFAULT "0"  COMMENT '用户性别',
	Nullity TINYINT NOT NULL DEFAULT "0"  COMMENT '禁止服务',
	NullityOverDate DATETIME NOT NULL DEFAULT "1900-01-01"  COMMENT '禁止时间',
	StunDown TINYINT NOT NULL DEFAULT "0"  COMMENT '关闭标识',
	MoorMachine TINYINT NOT NULL DEFAULT "0"  COMMENT '固定机器', 
	WebLoginTimes INT NOT NULL DEFAULT "0"  COMMENT '登录次数',
	GameLoginTimes INT NOT NULL DEFAULT "0"  COMMENT '登录次数',
	PlayTimeCount INT NOT NULL DEFAULT "0"  COMMENT '游戏时间',
	OnLineTimeCount INT NOT NULL DEFAULT ""  COMMENT '',
	LastLoginIP NVARCHAR(15) NOT NULL,
	LastLoginDate DATETIME NOT NULL,
	LastLoginMacine NVARCHAR(32) NOT NULL,
	RegisterIP NVARCHAR(15) NOT NULL,
	RegisterDate DATETIME NOT NULL,
	RegisterMachine NVARCHAR(32) NOT NULL,
	PRIMARY KEY (UserID)
);

CREATE TABLE ConfineAddress(
	AddrString NVARCHAR(15) NOT NULL,
	EnjoinLogin BIT NOT NULL,
	EnjoinRegister BIT NOT NULL,
	EnjoinOverDate DATETIME,
	CollectDate DATETIME NOT NULL,
	CollectNote NVARCHAR(32) NOT NULL,
	PRIMARY KEY (AddrString)
);
CREATE TABLE ConfineMachine(
	MachineSerial NVARCHAR(32) NOT NULL,
	EnjoinLogin BIT NOT NULL,
	EnjoinRegister BIT NOT NULL,
	EnjoinOverDate DATETIME,
	CollectDate DATETIME NOT NULL,
	CollectNote NVARCHAR(32) NOT NULL,
	PRIMARY KEY (MachineSerial)
);

CREATE TABLE GameIdentifier(
	UserID INT NOT NULL,
	Accounts NVARCHAR(16) NOT NULL,
	IDLevel INT NOT NULL,
	PRIMARY KEY (UserID)
);

CREATE TABLE IndividualDatum(
	UserID INT NOT NULL,
	Compellation NVARCHAR(16) NOT NULL,
	QQ NVARCHAR(16) NOT NULL,
	Email NVARCHAR(32) NOT NULL,
	MobilePhone NVARCHAR(16) NOT NULL,
	CollectDate DATETIME NOT NULL,
	UserNote NVARCHAR(256) NOT NULL,
	PRIMARY KEY(UserID)

);


CREATE TABLE SystemGrantCount(
	DateID INT NOT NULL,
	RegisterIP NVARCHAR(15) NOT NULL,
	RegisterMachine NVARCHAR(32) NOT NULL,
	GrantScore BIGINT NOT NULL,
	GrantCount BIGINT NOT NULL,
	CollectDate DATETIME NOT NULL,
	PRIMARY KEY(DateID)
);


CREATE TABLE SystemStatusInfo(
	StatusName NVARCHAR(32) NOT NULL,
	StatusValue INT NOT NULL,
	StatusString NVARCHAR(512) NOT NULL,
	StatusTip NVARCHAR(50) NOT NULL,
	StatusDescription NVARCHAR(100) NOT NULL,
	PRIMARY KEY(StatusName)
);

CREATE TABLE SystemStreamInfo(
	DateID INT NOT NULL,
	WebLoginSuccess INT NOT NULL,
	WebRegisterSuccess INT NOT NULL,
	GameLoginSuccess INT NOT NULL,
	CollectDate DATETIME NOT NULL,
	PRIMARY KEY (DateID)
);




